// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package usersettings

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/aiven/terraform-provider-aiven/internal/plugin/adapter"
)

func resourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Resource ID composed as: `project/service_name/username`.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"project": schema.StringAttribute{
				MarkdownDescription: "Project name. Changing this property forces recreation of the resource.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Required:            true,
			},
			"service_name": schema.StringAttribute{
				MarkdownDescription: "Service name. Changing this property forces recreation of the resource.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Required:            true,
			},
			"settings": schema.MapAttribute{
				ElementType:         types.StringType,
				MarkdownDescription: "Direct ClickHouse settings for the user, keyed by setting name, with values written exactly as ClickHouse stores them in `system.settings_profile_elements`. Set `{}` to remove them all.",
				Required:            true,
			},
			"username": schema.StringAttribute{
				MarkdownDescription: "Name of the ClickHouse user. Maximum length: `64`. Changing this property forces recreation of the resource.",
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Required:            true,
				Validators:          []validator.String{stringvalidator.LengthAtMost(64)},
			},
		},
		Blocks:              map[string]schema.Block{"timeouts": timeouts.BlockAll(ctx)},
		MarkdownDescription: "Manages the direct ClickHouse settings of an Aiven for ClickHouse user. Use one resource per user: it owns all direct settings of the user, so settings missing from `settings` are removed. Deleting the resource removes all direct settings of the user. The API token requires the `service:data:write` permission. If this resource is missing (for example, after a service power off), it's removed from the state and a new create plan is generated.",
	}
}
func resourceSchemaInternal() *adapter.Schema {
	return &adapter.Schema{
		Properties: map[string]*adapter.Schema{
			"id": &adapter.Schema{
				Computed: true,
				Type:     adapter.SchemaTypeString,
			},
			"project":      &adapter.Schema{Type: adapter.SchemaTypeString},
			"service_name": &adapter.Schema{Type: adapter.SchemaTypeString},
			"settings": &adapter.Schema{
				Items: &adapter.Schema{
					Type:           adapter.SchemaTypeString,
					ZeroNotAllowed: true,
				},
				Type: adapter.SchemaTypeMap,
			},
			"timeouts": &adapter.Schema{
				Properties: map[string]*adapter.Schema{
					"create": &adapter.Schema{Type: adapter.SchemaTypeString},
					"delete": &adapter.Schema{Type: adapter.SchemaTypeString},
					"read":   &adapter.Schema{Type: adapter.SchemaTypeString},
					"update": &adapter.Schema{Type: adapter.SchemaTypeString},
				},
				Type: adapter.SchemaTypeObject,
			},
			"username": &adapter.Schema{Type: adapter.SchemaTypeString},
		},
		Type: adapter.SchemaTypeObject,
	}
}
