// Copyright (c) 2026 Aiven, Helsinki, Finland. https://aiven.io/
// Code generated by user config generator. DO NOT EDIT.

package usersettings

const typeName = "aiven_clickhouse_user_settings"

// idFields the ID attribute fields, i.e.:
// terraform import aiven_clickhouse_user_settings.foo PROJECT/SERVICE_NAME/USERNAME
func idFields() []string {
	return []string{"project", "service_name", "username"}
}
